import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import qs from "qs";

import Button from "../components/Button";
import Footer from "../components/Footer";
import Header from "../components/Header";

type Props = {
  data: {
    id: number;
    attributes: {
      pageTitle: string;
      pageDescription: string;
    };
  };
};

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Button>Hello</Button>

      <Footer />
    </>
  );
};

// export async function getStaticProps() {
//   const stringifiedParams = qs.stringify(
//     {
//       populate: {
//         mainImage: {
//           fields: "id",
//         },
//       },
//     },
//     {
//       encodeValuesOnly: true,
//     }
//   );

//   console.log(`http://localhost:1337/api/homepage?${stringifiedParams}`);

//   const response = await fetch(
//     `http://localhost:1337/api/homepage?${stringifiedParams}`,
//     {
//       method: "GET",
//     }
//   );
//   const data = await response.json();

//   return { props: { ...data } };
// }

export default Home;
