import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import qs from "qs";

import Button from "../components/Button";
import Footer from "../components/Footer";
import Header from "../components/Header";

type Props = {
  data: {
    id: number;
    attributes: {
      pageTitle: string;
      pageDescription: string;
    };
  };
};

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Button>Hello</Button>
    </>
  );
};

export default Home;
